### ISSUE TITLE
Using Bluetooth Mopeka Sensor with Genmon-ESP32-Serial-Bridge

### ISSUE THREAD

**Issue by chriskinal** [gregmac/Genmon-ESP32-Serial-Bridge#21]
Has anyone done this before? Any ideas on where to start?

**Comment by gmn42** [comment]
I haven't, but why would you want to try to connect it to the esphome
instance on the bridge, rather than the genmon instance itself?  Genmon has
mopeka support built in (under add-ons).

**Comment by chriskinal** [comment]
I am consolidating all the various Pi's and small x86 servers onto VM's on a Proxmox cluster in the house. The generator and propane tank are a good distance from the house. There are outdoor WAP's on the buildings around the property so the ESP32 bridge can reach one of those but not the house. I don't think the Bluetooth from the Mopeka will reach the house reliably so I thought to use the ESP32 bridge to also forward the Mopeka Bluetooth serial data over the ESP32 bridge on a separate port.

**Comment by gmn42** [comment]
Interesting... it looks like it might be easy to use the mopeka_std_check or mopeka_pro_check sensors to surface the mopeka data in Home Assistant, but if you're trying to get it to Genmon it might need some tweaking because the genmon mopeka integration seems to be oriented toward using the on-board bluetooth on the host (e.g., a raspberry pi.).  There are the ble_proxy and ble_client ESPHome components, but I don't see how to use them to pass serial data to a TCP port; they just seem to expose it to HA.  Also, there's a big warning about memory usage with the ESP bluetooth stack that might be an issue if you're also using the serial proxy.

Please post an update if you have any luck, I know someone with a similar problem where the mopeka is too far from the house.

**Comment by chriskinal** [comment]
Actually, I use Genmon to get the data to Homeassistant via MQTT. I monitor the system via the dashboard you created. I tried the Homeassistant Bluetooth Proxy and it worked like a champ. I had an M5Stick laying around and it makes the perfect proxy.
